---
language: ruby
cache: bundler
rvm:
- 2.4.5
- 2.5.3
env:
- BUNDLER_VERSION=1.15
- BUNDLER_VERSION=1.16
- BUNDLER_VERSION=1.17
- BUNDLER_VERSION=2.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc --no-document'' > ~/.gemrc'
- gem install bundler -v "~> $BUNDLER_VERSION"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
